"""
Evidence and Finding data models for Auton v2.

Structures for capturing confirmed findings with evidence,
used by the Reporter agent to generate the final pentest report.
"""

from dataclasses import dataclass, field
from typing import List, Optional, Dict
from enum import Enum
from datetime import datetime


class Severity(Enum):
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFO = "info"


class EvidenceType(Enum):
    SCREENSHOT = "screenshot"
    HTTP_REQUEST = "http_request"
    HTTP_RESPONSE = "http_response"
    DOM_SNAPSHOT = "dom_snapshot"
    JS_CONSOLE = "js_console"
    COMMAND_OUTPUT = "command_output"
    LOG_ENTRY = "log_entry"


@dataclass
class Evidence:
    """A single piece of evidence supporting a finding."""
    type: EvidenceType
    content: str                  # The actual evidence data
    description: str = ""         # Human-readable explanation
    timestamp: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    
    def to_dict(self) -> dict:
        return {
            "type": self.type.value,
            "content": self.content,
            "description": self.description,
            "timestamp": self.timestamp,
        }


@dataclass
class Finding:
    """
    A confirmed vulnerability finding with full evidence chain.
    
    Generated by the Verifier agent and formatted by the Reporter.
    Maps to a CONFIRMED node in the AttackGraph.
    """
    id: str
    title: str
    severity: Severity
    description: str                         # What was found
    impact: str                              # Why it matters
    reproduction_steps: List[str]            # How to reproduce
    remediation: str                         # How to fix
    evidence: List[Evidence] = field(default_factory=list)
    
    # Graph references
    graph_node_id: str = ""                  # Links back to the AttackGraph node
    attack_path: List[str] = field(default_factory=list)  # Node IDs in the path
    
    # Classification
    cwe_id: Optional[str] = None             # e.g., "CWE-79"
    owasp_category: Optional[str] = None     # e.g., "A03:2021 - Injection"
    cvss_score: Optional[float] = None
    
    # Metadata
    discovered_by: str = ""                  # Agent that found it
    verified_by: str = ""                    # Agent that confirmed it
    created_at: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    
    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "title": self.title,
            "severity": self.severity.value,
            "description": self.description,
            "impact": self.impact,
            "reproduction_steps": self.reproduction_steps,
            "remediation": self.remediation,
            "evidence": [e.to_dict() for e in self.evidence],
            "classification": {
                "cwe": self.cwe_id,
                "owasp": self.owasp_category,
                "cvss": self.cvss_score,
            },
            "graph_node_id": self.graph_node_id,
            "attack_path": self.attack_path,
            "discovered_by": self.discovered_by,
            "verified_by": self.verified_by,
            "created_at": self.created_at,
        }
    
    def to_report_markdown(self) -> str:
        """Format as a single finding entry for the final report."""
        lines = [
            f"### {self.title}",
            f"**Severity**: {self.severity.value.upper()}",
            f"**CWE**: {self.cwe_id or 'N/A'} | **OWASP**: {self.owasp_category or 'N/A'}",
            f"",
            f"**Description**: {self.description}",
            f"",
            f"**Impact**: {self.impact}",
            f"",
            f"**Reproduction Steps**:",
        ]
        for i, step in enumerate(self.reproduction_steps, 1):
            lines.append(f"{i}. {step}")
        
        lines.append(f"")
        lines.append(f"**Remediation**: {self.remediation}")
        
        if self.evidence:
            lines.append(f"")
            lines.append(f"**Evidence** ({len(self.evidence)} items):")
            for ev in self.evidence:
                lines.append(f"- [{ev.type.value}] {ev.description}")
        
        return "\n".join(lines)


@dataclass
class PentestReport:
    """Complete pentest report aggregating all findings."""
    engagement_name: str
    target: str
    findings: List[Finding] = field(default_factory=list)
    executive_summary: str = ""
    methodology: str = ""
    created_at: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    
    def add_finding(self, finding: Finding):
        self.findings.append(finding)
    
    def get_by_severity(self, severity: Severity) -> List[Finding]:
        return [f for f in self.findings if f.severity == severity]
    
    def to_markdown(self) -> str:
        """Generate the full pentest report as markdown."""
        lines = [
            f"# Penetration Test Report: {self.engagement_name}",
            f"**Target**: {self.target}",
            f"**Date**: {self.created_at}",
            f"",
            f"## Executive Summary",
            self.executive_summary or "_To be generated by Reporter agent._",
            f"",
            f"## Findings Summary",
            f"| Severity | Count |",
            f"|----------|-------|",
        ]
        
        for sev in Severity:
            count = len(self.get_by_severity(sev))
            if count > 0:
                lines.append(f"| {sev.value.upper()} | {count} |")
        
        lines.append(f"")
        lines.append(f"## Detailed Findings")
        
        # Sort by severity (critical first)
        severity_order = [Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, 
                          Severity.LOW, Severity.INFO]
        for sev in severity_order:
            for finding in self.get_by_severity(sev):
                lines.append(f"")
                lines.append(finding.to_report_markdown())
        
        return "\n".join(lines)
